### ISSUE TITLE
Bower support?

### ISSUE THREAD

**Issue by wolxXx** [haroldiedema/joii#13]
Hello. 

First of all: thank you for that awesome project! 

Is it possible to add joii to bower packages? I would really appreciate that! 

http://bower.io/docs/creating-packages/#register

Thank you :)

**Comment by haroldiedema** [comment]
Hmm, as strange as it might seem, I've never worked with Bower... I'll have a look at it :+1:

**Comment by haroldiedema** [comment]
Done ;)

Let me know if something's wrong with it.

**Comment by wolxXx** [comment]
looks good, thx :) 

but while installing these warnings occurred: 
bower joii#*              invalid-meta joii is missing "main" entry in bower.json
bower joii#*              invalid-meta joii is missing "ignore" entry in bower.json

but all there, all fine. 
awesome!
