### ISSUE TITLE
Call a method inside a 'middle' class doesn't work

### ISSUE THREAD

**Issue by mpccolorado** [haroldiedema/joii#19]
If you create a hierarchy of classes of three levels for example you cannot invoke a method inside the class in the middle level...

    var Component = Class('Component',{
        'public init': function(component){
            console.log('Component -> init method');
        }
    });

    var SimpleComponent = Class('SimpleComponent', {extends: Component}, {
        'public init': function(component){
            console.log('SimpleComponent -> init method')
            this.super('init', component);
            this.start(500);
         },
         'public start': function(milliseconds){            
            console.log("start method");
         }
    });

    var ExtraComponent = Class('ExtraComponent',{extends: SimpleComponent}, {
        'public init': function(component){
            console.log('ExtraComponent -> init method')
            this.super('init', component);
        }
    });

    var newComponent = new ExtraComponent();
    newComponent.init({});

This error occurs when trying to execute __this.start(500);__ inside the __init__ method on the __SimpleComponent__ class:

    Error: "scope.__api__ is undefined"

I created a [plunker](http://plnkr.co/edit/pAW80ndZDUvh7Wmn2MV7)

**Comment by haroldiedema** [comment]
Thanks for the report. I'll take a look at it and report back when I find something.

**Comment by haroldiedema** [comment]
Alright, so I found a little issue...

In PrototypeBuilder.js @ line 132, no recursion takes place over the implemented parent classes. I tried creating a hierarchy of 16 classes, and each time only 2 of them (the current one and direct parent) is shown in the implementation list.

This is _part_ of the issue that you're describing. I think fixing this would also (maybe partially) fix yours.

**Comment by haroldiedema** [comment]
Okay.

I found a solution. Commit incoming.

**Comment by mpccolorado** [comment]
Great! I will look into it when you push the changes.

Thanks for the quick response!

**Comment by haroldiedema** [comment]
Let me know if this really fixed it. If not, please provide a new test-case so I can look into it. Will do it tomorrow though, had a long day ;)

Enjoy!
