### ISSUE TITLE
Interface collisions

### ISSUE THREAD

**Issue by mpccolorado** [haroldiedema/joii#21]
If I declare two interfaces:

    var InterfaceA = Interface('InterfaceA', {
	    'public method': function(){ }
    });

    var InterfaceB = Interface('InterfaceB', {
	    'public anotherMethod': function(){ }
    });

and implement one interface:

    var ImplementedA = Class('ImplementedA', {implements: InterfaceA}, {
	    'public method': function(){}
    }

and I declare some property with the type of the first one (and the second one was the last loaded) like this:

    var SomeClass = Class('SomeClass', {}, {
        'public nullable InterfaceA interfaceAObject': null
    }

and then try to initialize the property with a correspondent object:

    var someClassObject = new SomeClass();
    var aObject = new ImplementedA();
    someClassObject.setInterfaceaobject(aObject);

then an exception is thrown telling that the property is wrong and must be of type InterfaceB...

**Comment by haroldiedema** [comment]
Fixed in 3.1.5, thanks for reporting :+1:
