### ISSUE TITLE
Broken visibility in setters

### ISSUE THREAD

**Issue by cjmanca** [haroldiedema/joii#25]
Example:

```javascript
var MyClass = Class({
        'public a': 1,
        'protected b': 2,
});

var mc = new MyClass();
var innerScope = mc.setA('10');
alert(innerScope['b']); // prints: 2
```

This will also be an issue when trying to return "this" from any custom function too. I'm unsure how to refer to the outer scope from a custom function to properly return a reference to the instance.

I can see a couple of possible fixes for this.
1. Provide an easy way to refer to the outer scope (maybe "self"?) and educate people on it.
2. Check the return value in the "bind" shim to see if they're returning the inner object, and replace it with the outer:
```javascript
    g.JOII.Compat.Bind = function(fn, context) {
        if (typeof fn !== "function") {
            // closest thing possible to the ECMAScript 5 internal IsCallable function
            throw new TypeError("Function.prototype.bind - argument #1 must be a function.");
        }

        // return fn.bind(context);

        return function bound() {
            var ret = fn.apply(context, arguments);
            if (ret == context) {
                ret = this;
            }
            return ret;
        };
    };
```
3. A serious overhaul of the way functions are called, so they execute in outer scope, and all private/protected properties and functions are "added" to the outer scope in the shim prior to executing, and removed from outer after the function finishes. This can have other potential security issues though if that custom function calls an external function, which then refers back to that object (since all internal properties/functions would be visible while that internal function is on the call stack). The only solution I see to this would be to intercept all outgoing function calls and detour them through another shim, again hiding the internals. Seems like a lot of extra effort, but would allow for worry free use of the "this" keyword.

**Comment by cjmanca** [comment]
I've since discovered that I can use:
```javascript
this.__api__
```
to return the outer scope, and another alternative to changing bind would be to change:
```javascript
setter_fn = new Function('v', (meta.type !== null ? validator : '') + 'this["' + meta.name + '"] = v; return this;');
```
to
```javascript
setter_fn = new Function('v', (meta.type !== null ? validator : '') + 'this["' + meta.name + '"] = v; return this.__api__;');
```
in g.JOII.CreatePropertyGetterSetter (PrototypeBuilder.js)

**Comment by haroldiedema** [comment]
Heh... Nice catch!

Working on a fix now.
