### ISSUE TITLE
Uncaught An abstract class cannot be instantiated.

### ISSUE THREAD

**Issue by buckelieg** [haroldiedema/joii#33]
Using JOII in browser and just implementing the examples (https://joii.harold.info/meta/abstract):

just adding this to the script:

var Base = Class({ abstract: true }, {
    'abstract public login(string, string)' : function (user, pass) {}
});

And getting an error:

joii-4.1.1.js:1689 Uncaught An abstract class cannot be instantiated.
generateInnerScope @ joii-4.1.1.js:1689
staticDefinition @ joii-4.1.1.js:1990
JOII.ClassBuilder @ joii-4.1.1.js:2079
(anonymous) @ tab.js:24

**Comment by haroldiedema** [comment]
Yes, this is correct behavior because an abstract class cannot be instantiated using the `new`-keyword. They can only be used as a parent class on children, as shown in the example.

The comment on line 5 in the example says so ;)

```javascript
// Throws an error: An abstract class cannot be instantiated.
new Base();
```

**Comment by buckelieg** [comment]
The thing is I am not instantiating this class - I leave JUST A DECLARATION of an abstract class.

Literally - JUST this line of code:

var Base = Class({ abstract: true }, {
'abstract public login(string, string)' : function (user, pass) {}
});
